services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME:-gateway}
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./services/api
    depends_on:
      - mongo
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "5001:5000"

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    restart: unless-stopped

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - "8081:8081"
    restart: unless-stopped
