services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME:-gateway}
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./services/api
    depends_on:
      - mongo
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
  mongo_data:
